import { NextResponse } from "next/server";
import {
  applySession,
  authedBackendFetch,
  backendUrl,
  clearSessionCookies,
  forwardedForHeader,
  readTokens,
  readJsonWithLimit,
} from "@/lib/auth/session";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

interface RequestBody {
  market?: unknown;
  persona?: unknown;
  customPersona?: unknown;
  selectedDocumentIds?: unknown;
}

function asString(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

function asStringArray(value: unknown): string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((v): v is string => typeof v === "string");
}

/**
 * POST /api/generate-workflow — the authenticated product route.
 *
 * There is **no TypeScript fallback here, by design**. A report produced on this
 * route belongs to a real account and is persisted to that account's tenant, so
 * it may only be generated by a session the backend has actually validated.
 * Falling back to the local pipeline when the backend is unreachable would mean
 * serving an authenticated-looking report to a session nobody verified — the
 * presence of a cookie is not evidence of anything.
 *
 * If the backend cannot validate the session, this returns **503**, and the
 * caller is told to retry.
 */
export async function POST(request: Request) {
  // Bounded before buffering: `request.json()` would read an unlimited body into
  // the Next process's memory before the backend's cap ever applied.
  const parsed = await readJsonWithLimit(request);
  if (!parsed.ok) return parsed.response;
  const body = (parsed.body ?? {}) as RequestBody;

  const input = {
    market: asString(body.market) || "EMEA",
    persona: asString(body.persona) || "Support Agent",
    customPersona: asString(body.customPersona),
    selectedDocumentIds: asStringArray(body.selectedDocumentIds),
  };

  const { accessToken, refreshToken } = await readTokens();
  if (!accessToken && !refreshToken) {
    return NextResponse.json(
      { code: "not_authenticated", error: "Sign in to generate a report." },
      { status: 401 },
    );
  }

  // Authentication is delegated to the backend. No backend ⇒ no way to validate
  // the session ⇒ we must not generate. This is a 503, not a silent fallback.
  if (!backendUrl()) {
    return NextResponse.json(
      {
        code: "backend_unavailable",
        error: "Report generation is temporarily unavailable. Please try again shortly.",
      },
      { status: 503 },
    );
  }

  const timeoutMs = Number(process.env.EVIDENTIA_BACKEND_TIMEOUT_MS) || 45000;

  try {
    const { res, rotated } = await authedBackendFetch(
      "/api/generate-workflow",
      { method: "POST", body: JSON.stringify(input) },
      timeoutMs,
      forwardedForHeader(request),
    );

    if (res.ok) {
      return applySession(NextResponse.json(await res.json(), { status: 200 }), rotated);
    }

    // The session is gone (expired, revoked, or reuse-detected). Clear the stale
    // cookies so the client stops presenting them, and say so plainly.
    if (res.status === 401) {
      return clearSessionCookies(
        NextResponse.json(
          { code: "not_authenticated", error: "Your session has expired. Please sign in again." },
          { status: 401 },
        ),
      );
    }
    if (res.status === 403 || res.status === 409) {
      const data = (await res.json().catch(() => ({}))) as { code?: string; detail?: string };
      const known = new Set([
        "tenant_generation_disabled",
        "tenant_corpus_empty",
        "tenant_corpus_ineligible",
        "company_membership_required",
      ]);
      const code = typeof data.code === "string" && known.has(data.code) ? data.code : "forbidden";
      return NextResponse.json(
        {
          code,
          error:
            code === "tenant_generation_disabled"
              ? "Tenant report generation is not enabled for this deployment."
              : code === "tenant_corpus_empty" || code === "tenant_corpus_ineligible"
                ? "Finalize at least one eligible document before generating a tenant report."
                : code === "company_membership_required"
                  ? "Join or create an organization before generating a tenant report."
                : typeof data.detail === "string"
                  ? data.detail
                  : "Not permitted.",
        },
        { status: res.status },
      );
    }

    // Pass the backend's throttling through verbatim, including Retry-After, so
    // the UI can tell the user how long to wait.
    if (res.status === 429) {
      const retryAfter = res.headers.get("retry-after");
      return NextResponse.json(
        {
          code: "rate_limited",
          error: "You've reached the generation limit. Please try again later.",
        },
        { status: 429, headers: retryAfter ? { "Retry-After": retryAfter } : undefined },
      );
    }

    if (res.status === 422) {
      const data = (await res.json().catch(() => ({}))) as { code?: string };
      if (data.code === "evidence_validation_failed") {
        return NextResponse.json(
          {
            code: "evidence_validation_failed",
            error: "Generated evidence could not be validated against the tenant snapshot.",
          },
          { status: 422 },
        );
      }
    }

    if (res.status === 413 || res.status === 422) {
      return NextResponse.json(
        { code: "invalid_request", error: "That request could not be processed." },
        { status: res.status },
      );
    }

    // A 503 from the backend is a *persistence* failure, not a transport failure:
    // the report was generated but could not be saved, so nothing exists to fetch.
    // The client must be told this is a failed attempt, never a successful report.
    if (res.status === 503) {
      const data = (await res.json().catch(() => ({}))) as { code?: string };
      const code =
        data?.code === "persistence_failed" || data?.code === "persistence_unavailable"
          ? data.code
          : data?.code === "tenant_retrieval_failed"
            ? data.code
          : "backend_unavailable";
      return NextResponse.json(
        {
          code,
          error:
            code === "backend_unavailable" || code === "tenant_retrieval_failed"
              ? "Report generation is temporarily unavailable. Please try again shortly."
              : "Your report could not be saved, so it was not created. Please try again.",
        },
        { status: 503 },
      );
    }

    console.warn(`[evidentia] backend generate returned ${res.status}`);
    return NextResponse.json(
      {
        code: "backend_unavailable",
        error: "Report generation is temporarily unavailable. Please try again shortly.",
      },
      { status: 503 },
    );
  } catch {
    // Network error / timeout. We cannot validate the session, so we cannot
    // generate an authenticated report. Never fall back.
    console.warn("[evidentia] backend unreachable during authenticated generation");
    return NextResponse.json(
      {
        code: "backend_unavailable",
        error: "Report generation is temporarily unavailable. Please try again shortly.",
      },
      { status: 503 },
    );
  }
}

export function GET() {
  return NextResponse.json(
    { message: "POST an AgentInput to generate an Evidentia report." },
    { status: 405 },
  );
}
