import type { DemoDoc, DocId } from "./types";

export const DEMO_DOCS: DemoDoc[] = [
  {
    id: "d1",
    name: "Security & Compliance Whitepaper",
    short: "Security Whitepaper",
    meta: "PDF · 48 pages · updated 12 days ago",
    kind: "PDF",
    description: "Encryption, access controls, and certification posture.",
    base: 70,
    filename: "security_compliance_whitepaper.pdf",
    category: "Security",
    pages: "48 pages",
    updatedAt: "Jun 22 2026",
    status: "Indexed",
    citationIds: ["SEC-4.2", "SEC-7.1"],
    usedByPersonas: ["Sales Engineer", "Compliance Officer", "Solutions Architect"],
    topics: ["Encryption", "Access control", "Certifications", "Audit"],
    sampleExcerpt:
      "All customer data is encrypted at rest using AES-256 and in transit via TLS 1.3.",
    relevanceTags: ["security", "compliance", "trust"],
  },
  {
    id: "d2",
    name: "Platform API Reference",
    short: "API Reference",
    meta: "HTML · 320 endpoints · versioned",
    kind: "HTML",
    description: "Endpoints, authentication, and rate limits.",
    base: 60,
    filename: "platform_api_reference.html",
    category: "API",
    pages: "320 endpoints",
    updatedAt: "Jul 01 2026",
    status: "Indexed",
    citationIds: ["API-RL", "API-2.4"],
    usedByPersonas: ["Solutions Architect", "Sales Engineer"],
    topics: ["Endpoints", "Auth", "Rate limits", "Webhooks"],
    sampleExcerpt: "Default account limit is 2,000 requests per minute, burstable to 5,000.",
    relevanceTags: ["api", "integration", "limits"],
  },
  {
    id: "d3",
    name: "SLA & Uptime Commitment",
    short: "SLA Commitment",
    meta: "PDF · 12 pages · legal-reviewed",
    kind: "PDF",
    description: "Availability targets, remedies, and credit terms.",
    base: 65,
    filename: "sla_uptime_commitment.pdf",
    category: "Reliability",
    pages: "12 pages",
    updatedAt: "May 30 2026",
    status: "Indexed",
    citationIds: ["SLA-3", "SLA-5"],
    usedByPersonas: ["Support Agent", "Operations Manager", "Sales Engineer"],
    topics: ["Availability", "Credits", "Remedies", "Multi-region"],
    sampleExcerpt:
      "Northreach commits to 99.99% monthly availability for multi-AZ Enterprise deployments.",
    relevanceTags: ["uptime", "reliability", "legal"],
  },
  {
    id: "d4",
    name: "Deployment & Migration Guide",
    short: "Deployment Guide",
    meta: "PDF · 86 pages · engineering",
    kind: "PDF",
    description: "Topologies, rollout patterns, and rollback.",
    base: 68,
    filename: "deployment_migration_guide.pdf",
    category: "Deployment",
    pages: "86 pages",
    updatedAt: "Jun 15 2026",
    status: "Indexed",
    citationIds: ["DEP-11", "DEP-4"],
    usedByPersonas: ["Solutions Architect", "Operations Manager", "New Hire"],
    topics: ["Topology", "Blue-green", "Rollback", "Migration"],
    sampleExcerpt:
      "Blue-green deployments are supported across all commercial regions with automated rollback.",
    relevanceTags: ["deployment", "architecture", "rollout"],
  },
  {
    id: "d5",
    name: "Data Residency & Sovereignty Policy",
    short: "Residency Policy",
    meta: "PDF · 24 pages · compliance",
    kind: "PDF",
    description: "Regional processing and data-locality rules.",
    base: 62,
    filename: "data_residency_policy.pdf",
    category: "Compliance",
    pages: "24 pages",
    updatedAt: "Jun 28 2026",
    status: "Indexed",
    citationIds: ["RES-14", "RES-9"],
    usedByPersonas: ["Compliance Officer", "Solutions Architect", "Sales Engineer"],
    topics: ["Residency", "Sovereignty", "In-region processing", "GDPR"],
    sampleExcerpt:
      "Default control-plane metadata is processed in us-east-1 unless in-region processing is provisioned.",
    relevanceTags: ["residency", "compliance", "emea"],
  },
  {
    id: "d6",
    name: "Incident Response Runbook",
    short: "Incident Runbook",
    meta: "Markdown · 31 pages · on-call",
    kind: "MD",
    description: "Severity matrix, escalation, and on-call paths.",
    base: 64,
    filename: "incident_response_runbook.md",
    category: "Operations",
    pages: "31 pages",
    updatedAt: "Jun 09 2026",
    status: "Indexed",
    citationIds: ["INC-2.1", "INC-6"],
    usedByPersonas: ["Support Agent", "Operations Manager", "New Hire"],
    topics: ["Severity matrix", "Escalation", "On-call", "Paging"],
    sampleExcerpt:
      "Severity 1 incidents page the primary on-call within 5 minutes via the escalation tool.",
    relevanceTags: ["incident", "on-call", "support"],
  },
  {
    id: "d7",
    name: "Pricing & Packaging Sheet",
    short: "Pricing Sheet",
    meta: "XLSX · 5 tabs · revenue ops",
    kind: "XLSX",
    description: "Tiers, add-ons, and overage structures.",
    base: 45,
    filename: "pricing_packaging_sheet.xlsx",
    category: "Pricing",
    pages: "5 tabs",
    updatedAt: "Jun 18 2026",
    status: "Indexed",
    citationIds: ["PRC-3", "PRC-1"],
    usedByPersonas: ["Operations Manager", "Sales Engineer"],
    topics: ["Tiers", "Add-ons", "Egress", "Overage"],
    sampleExcerpt:
      "Enterprise tier includes 10 TB egress per month; overage tiers are not yet published.",
    relevanceTags: ["pricing", "revenue", "cost"],
  },
  {
    id: "d8",
    name: "Customer Onboarding Handbook",
    short: "Onboarding Handbook",
    meta: "PDF · 40 pages · enablement",
    kind: "PDF",
    description: "Ramp path, roles, and platform basics.",
    base: 40,
    filename: "customer_onboarding_handbook.pdf",
    category: "Enablement",
    pages: "40 pages",
    updatedAt: "May 24 2026",
    status: "Indexed",
    citationIds: ["ONB-1", "ONB-8"],
    usedByPersonas: ["New Hire", "Support Agent"],
    topics: ["Ramp path", "Roles", "Platform basics", "Escalation contacts"],
    sampleExcerpt:
      "New team members complete platform fundamentals and the severity matrix in the first two weeks.",
    relevanceTags: ["onboarding", "enablement", "ramp"],
  },
];

export const DEFAULT_PICKED: DocId[] = ["d1", "d3", "d4", "d8"];

export function getDoc(id: DocId): DemoDoc | undefined {
  return DEMO_DOCS.find((d) => d.id === id);
}
